"""Generate the statement tables from real Alpha Vantage files.

Reads the field names out of sample JSON files (the field set is the same for every
company), and writes:
  supabase/migrations/20261005010000_statement_tables.sql   the four wide raw tables
  ingest/columns.py                                         camelCase field -> column map

Usage:  python tools/gen_statement_tables.py "<path to Raw Data folder>"

Never edit the outputs by hand. If Alpha Vantage adds a field, the ingest job keeps it in
the `extra` column; to promote it to a real column, rerun this and write a new
migration with `alter table ... add column`.
"""
import json
import re
import sys
from pathlib import Path

RAW = Path(sys.argv[1])
SAMPLE_FILES = 30
ROOT = Path(__file__).resolve().parent.parent

# statement -> (folder, annual list key, quarterly list key, table, per-period text columns)
SPEC = {
    "income":   ("IncomeStatement", "annualReports",  "quarterlyReports",  "income_statement_raw", "reported_currency text"),
    "balance":  ("BalanceSheet",    "annualReports",  "quarterlyReports",  "balance_sheet_raw",    "reported_currency text"),
    "cashflow": ("CashFlows",       "annualReports",  "quarterlyReports",  "cash_flow_raw",        "reported_currency text"),
    "earnings": ("Earnings",        "annualEarnings", "quarterlyEarnings", "earnings_raw",         "reported_date date,\n  report_time text"),
}
PERIOD_FIELDS = {"fiscalDateEnding", "reportedCurrency", "reportedDate", "reportTime"}


def snake(name):
    # Postgres silently cuts identifiers at 63 bytes, so cut here too and the ingest map matches
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name).lower()[:63]


fields = {}
for stmt, (folder, annual_key, quarterly_key, table, _) in SPEC.items():
    seen = {}
    files = sorted((RAW / folder).glob("*.json"))[:SAMPLE_FILES]
    if not files:
        sys.exit(f"no json files in {RAW / folder}")
    for f in files:
        data = json.loads(f.read_text(encoding="utf-8"))
        for key in (annual_key, quarterly_key):
            for report in data.get(key, []):
                for k in report:
                    if k not in PERIOD_FIELDS:
                        seen.setdefault(k, snake(k))
    cols = list(seen.values())
    if len(set(cols)) != len(cols):
        dupes = sorted({c for c in cols if cols.count(c) > 1})
        sys.exit(f"{stmt}: column name collision after shortening: {dupes}")
    fields[stmt] = seen
    print(f"{stmt:9} {len(files)} files sampled, {len(seen)} fields")

sql = [
    "-- GENERATED by tools/gen_statement_tables.py from real Alpha Vantage files. Do not edit by hand.",
    "--",
    "-- Wide tables: one row per symbol + period + fiscal date, one typed column per Alpha Vantage field.",
    "-- (One row per value was ~5.6M rows for 640 tickers; this is ~65k rows per statement.)",
    "-- Raw = exactly what Alpha Vantage sent. Corrections live in statement_override and are applied",
    "-- by the views in the next migration. `None` / `-` from Alpha Vantage is stored as null.",
    "-- Field names that Alpha Vantage may add later land in `extra` until promoted to a column.",
    "",
]
for stmt, (_, _, _, table, text_cols) in SPEC.items():
    col_lines = ",\n".join(f"  {c} numeric" for c in fields[stmt].values())
    sql.append(f"""create table public.{table} (
  symbol             text not null references public.ticker(symbol) on delete cascade,
  period             text not null check (period in ('annual', 'quarterly')),
  fiscal_date_ending date not null,
  -- statements join on year-month, like the Power BI model, so a one-day date difference does not break a match
  year_month         date generated always as (public.month_start(fiscal_date_ending)) stored,
  {text_cols},
{col_lines},
  extra              jsonb,
  fetched_at         timestamptz not null default now(),
  primary key (symbol, period, fiscal_date_ending),
  unique (symbol, period, year_month)
);
""")

out_sql = ROOT / "supabase" / "migrations" / "20261005010000_statement_tables.sql"
out_sql.write_text("\n".join(sql), encoding="utf-8", newline="\n")

py = ['"""GENERATED by tools/gen_statement_tables.py. Do not edit by hand."""', "", "STATEMENT_FIELDS = {"]
for stmt, seen in fields.items():
    py.append(f'    "{stmt}": {{')
    py.extend(f'        "{k}": "{v}",' for k, v in seen.items())
    py.append("    },")
py.append("}")
(ROOT / "ingest" / "columns.py").write_text("\n".join(py) + "\n", encoding="utf-8", newline="\n")

print(f"wrote {out_sql.relative_to(ROOT)} and ingest/columns.py")
